FROM balenalib/%%BALENA_ARCH%%-alpine-node:14-build as build

# Required since dbus package install compiles some code
RUN apk add --no-cache dbus-dev

# Install node dependencies
COPY package*.json ./
RUN npm install --production && npm cache clean --force && rm -rf /tmp/*


FROM balenalib/%%BALENA_ARCH%%-alpine-node:14-run as run

WORKDIR /app
COPY --from=build ./node_modules ./node_modules
COPY index.js package.json ./

# Start the container
CMD ["npm", "start"]
