FROM balenalib/%%BALENA_ARCH%%-alpine-node:14-build as build

# Install node dependencies
COPY package*.json ./
RUN npm install --production && npm cache clean --force && rm -rf /tmp/*


FROM balenalib/%%BALENA_ARCH%%-alpine-node:14-run as run

# Required for systeminformation disk metrics
RUN apk update && apk add --no-cache lsblk

WORKDIR /app
COPY --from=build ./node_modules ./node_modules
COPY index.js package.json ./

# Start the container
CMD ["npm", "start"]
