version: '2'
services:
  system-metrics:
    image: kb2ma/system-metrics
    restart: unless-stopped
    privileged: true
    network_mode: host
    labels:
      io.balena.features.dbus: '1'
    environment:
      MQTT_ADDRESS: '127.0.0.1'
      DISPLAY: ':0'
      DBUS_SYSTEM_BUS_ADDRESS: 'unix:path=/host/run/dbus/system_bus_socket'
    depends_on:
        - "mqtt"
