version: '2'
services:
  sensor:
    build: ./system-metrics
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      MQTT_ADDRESS: '127.0.0.1'
      # for example purposes; default log level is 'info'
      LOG_LEVEL: debug
    depends_on:
        - "mqtt"
  mqtt:
    image: eclipse-mosquitto:1.6.15
    # need host exposure for sensor service, but limit to just this host for security
    ports:
      - 127.0.0.1:1883:1883
    restart: always  
